#!/bin/sh

set -e

if [ "$1" != configure ]; then exit 0; fi

if [ -d /usr/doc -a ! -e /usr/doc/lynx -a -d /usr/share/doc/lynx ]; then
    ln -sf ../share/doc/lynx /usr/doc/lynx
fi

if [ -x /usr/bin/update-menus ]; then
    update-menus
fi

if [ -x /usr/sbin/update-mime ]; then
    update-mime
fi
