#!/bin/sh

set -e

if [ "$1" != configure ]; then exit 0; fi

if [ -x /usr/bin/update-menus ]; then
    update-menus
fi

if [ -x /usr/sbin/update-mime ]; then
    update-mime
fi

update-alternatives --quiet --install /usr/bin/www-browser www-browser \
       /usr/bin/lynx 50 \
       --slave /usr/share/man/man1/www-browser.1.gz www-browser.1.gz \
       /usr/share/man/man1/lynx.1.gz

update-alternatives --quiet --install /usr/bin/lynx lynx /usr/bin/lynx.stable 20
